<?php
namespace NumbersPHP;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-22 at 19:16:10.
 */
class CalculusTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Calculus
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Calculus;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers NumbersPHP\Calculus::pointDiff
     * @todo   Implement testPointDiff().
     */
    public function testPointDiff()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Calculus::riemann
     * @todo   Implement testRiemann().
     */
    public function testRiemann()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Calculus::simpsonDef
     * @todo   Implement testSimpsonDef().
     */
    public function testSimpsonDef()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Calculus::simpsonRecursive
     * @todo   Implement testSimpsonRecursive().
     */
    public function testSimpsonRecursive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Calculus::adaptiveSimpson
     * @todo   Implement testAdaptiveSimpson().
     */
    public function testAdaptiveSimpson()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Calculus::limit
     * @todo   Implement testLimit().
     */
    public function testLimit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Calculus::stirlingGamma
     * @todo   Implement testStirlingGamma().
     */
    public function testStirlingGamma()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Calculus::lanczosGamma
     * @todo   Implement testLanczosGamma().
     */
    public function testLanczosGamma()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
