<?php
namespace NumbersPHP;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-25 at 11:51:24.
 */
class StatisticTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Statistic
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Statistic;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers NumbersPHP\Statistic::mean
     * @todo   Implement testMean().
     */
    public function testMean()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Statistic::median
     * @todo   Implement testMedian().
     */
    public function testMedian()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Statistic::mode
     * @todo   Implement testMode().
     */
    public function testMode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Statistic::quantile
     * @todo   Implement testQuantile().
     */
    public function testQuantile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Statistic::report
     * @todo   Implement testReport().
     */
    public function testReport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Statistic::randomSample
     * @todo   Implement testRandomSample().
     */
    public function testRandomSample()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Statistic::standardDev
     * @todo   Implement testStandardDev().
     */
    public function testStandardDev()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Statistic::correlation
     * @todo   Implement testCorrelation().
     */
    public function testCorrelation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Statistic::rSquared
     * @todo   Implement testRSquared().
     */
    public function testRSquared()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Statistic::exponentialRegression
     * @todo   Implement testExponentialRegression().
     */
    public function testExponentialRegression()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Statistic::linearRegression
     * @todo   Implement testLinearRegression().
     */
    public function testLinearRegression()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NumbersPHP\Statistic::covariance
     * @todo   Implement testCovariance().
     */
    public function testCovariance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
